#!/bin/bash

echo "🔍 VERIFICANDO PROBLEMAS DO REACT"
echo "================================="
echo ""

echo "1️⃣ Vá para a aba Console no DevTools"
echo "2️⃣ Procure por erros em vermelho"
echo ""
echo "Erros comuns:"
echo "- 'Cannot read property of undefined'"
echo "- 'Module not found'"
echo "- 'Failed to fetch'"
echo ""
echo "3️⃣ Se não houver erros no Console, tente:"
echo ""
echo "a) No Console, digite:"
echo "   console.log(document.getElementById('root'))"
echo "   (deve mostrar <div id='root'>)"
echo ""
echo "b) Digite também:"
echo "   console.log(window.React)"
echo "   (deve mostrar o objeto React)"
echo ""
echo "4️⃣ Compartilhe comigo:"
echo "- Screenshot do Console com os erros"
echo "- O resultado dos comandos acima" 